var hierarchy =
[
    [ "vae::core::memory::Allocator< T, NAME >", "structvae_1_1core_1_1memory_1_1_allocator.html", null ],
    [ "vae::core::memory::AudioAllocatorName", "structvae_1_1core_1_1memory_1_1_audio_allocator_name.html", null ],
    [ "tklb::AudioBufferTpl< T, STORAGE >", "classtklb_1_1_audio_buffer_tpl.html", null ],
    [ "tklb::AudioBufferTpl< double >", "classtklb_1_1_audio_buffer_tpl.html", null ],
    [ "tklb::AudioBufferTpl< float >", "classtklb_1_1_audio_buffer_tpl.html", null ],
    [ "tklb::AudioBufferTpl< Sample, tklb::HeapBuffer< Sample, tklb::DEFAULT_ALIGNMENT, memory::AllocatorAudio< unsigned char > > >", "classtklb_1_1_audio_buffer_tpl.html", null ],
    [ "tklb::AudioBufferTpl< Sample, tklb::HeapBuffer< Sample, tklb::DEFAULT_ALIGNMENT, memory::AllocatorScratch< unsigned char > > >", "classtklb_1_1_audio_buffer_tpl.html", [
      [ "tklb::AudioRingBufferTpl< Sample, tklb::HeapBuffer< Sample, tklb::DEFAULT_ALIGNMENT, memory::AllocatorScratch< unsigned char > > >", "classtklb_1_1_audio_ring_buffer_tpl.html", null ]
    ] ],
    [ "tklb::AudioBufferTpl< T, HeapBuffer< T, DEFAULT_ALIGNMENT > >", "classtklb_1_1_audio_buffer_tpl.html", [
      [ "tklb::AudioRingBufferTpl< T, STORAGE >", "classtklb_1_1_audio_ring_buffer_tpl.html", null ]
    ] ],
    [ "vae::core::Device::AudioThreadWorker", "structvae_1_1core_1_1_device_1_1_audio_thread_worker.html", null ],
    [ "vae::core::Backend", "classvae_1_1core_1_1_backend.html", [
      [ "vae::core::BackendDummy", "classvae_1_1core_1_1_backend_dummy.html", null ],
      [ "vae::core::BackendPortAudio", "classvae_1_1core_1_1_backend_port_audio.html", null ],
      [ "vae::core::BackendRtAudio", "classvae_1_1core_1_1_backend_rt_audio.html", null ]
    ] ],
    [ "vae::core::Bank", "structvae_1_1core_1_1_bank.html", null ],
    [ "vaeb::Bank1", "structvaeb_1_1_bank1.html", null ],
    [ "vaeb::Bank2", "structvaeb_1_1_bank2.html", null ],
    [ "vae::core::BankLoader", "classvae_1_1core_1_1_bank_loader.html", null ],
    [ "vae::core::BankManager", "classvae_1_1core_1_1_bank_manager.html", null ],
    [ "tklb::BaseDelegate< Parameters >", "classtklb_1_1_base_delegate.html", null ],
    [ "tklb::BaseDelegate< Parameters... >", "classtklb_1_1_base_delegate.html", [
      [ "tklb::Delegate< void(Parameters...)>", "structtklb_1_1_delegate_3_01void_07_parameters_8_8_8_08_4.html", null ]
    ] ],
    [ "tklb::EventBus< EVENT_COUNT, EventId, MutexType >::BaseSubscription", "classtklb_1_1_event_bus_1_1_base_subscription.html", [
      [ "tklb::EventBus< EVENT_COUNT, EventId, MutexType >::Subscription< Parameters >", "classtklb_1_1_event_bus_1_1_subscription.html", null ]
    ] ],
    [ "tklb::memory::MemoryPool::Block", "structtklb_1_1memory_1_1_memory_pool_1_1_block.html", null ],
    [ "vae::core::Listener::Configuration", "structvae_1_1core_1_1_listener_1_1_configuration.html", null ],
    [ "vae::core::Convolve", "structvae_1_1core_1_1_convolve.html", null ],
    [ "tklb::ConvolverBruteTpl< T >", "classtklb_1_1_convolver_brute_tpl.html", null ],
    [ "tklb::ConvolverMonoTpl< T >", "classtklb_1_1_convolver_mono_tpl.html", null ],
    [ "tklb::ConvolverRefTpl< T >", "classtklb_1_1_convolver_ref_tpl.html", null ],
    [ "tklb::ConvolverTpl< T >", "classtklb_1_1_convolver_tpl.html", null ],
    [ "tklb::Delegate< Parameters >", "structtklb_1_1_delegate.html", null ],
    [ "tklb::Delegate< void(Device *)>", "structtklb_1_1_delegate.html", null ],
    [ "tklb::DelegateFactory< T, Parameters >", "structtklb_1_1_delegate_factory.html", null ],
    [ "vae::core::Device", "classvae_1_1core_1_1_device.html", [
      [ "vae::core::DeviceDummy", "classvae_1_1core_1_1_device_dummy.html", null ],
      [ "vae::core::DevicePortaudio", "classvae_1_1core_1_1_device_portaudio.html", null ],
      [ "vae::core::DeviceRtaudio", "classvae_1_1core_1_1_device_rtaudio.html", null ]
    ] ],
    [ "vae::DeviceInfo", "structvae_1_1_device_info.html", null ],
    [ "vae::core::Effect", "structvae_1_1core_1_1_effect.html", null ],
    [ "vae::core::effect::EffectBase", "classvae_1_1core_1_1effect_1_1_effect_base.html", [
      [ "vae::core::effect::FaustBase", "classvae_1_1core_1_1effect_1_1_faust_base.html", [
        [ "vae::core::effect::VAEReverb", "classvae_1_1core_1_1effect_1_1_v_a_e_reverb.html", null ]
      ] ]
    ] ],
    [ "vae::core::effect::EffectsFactory", "classvae_1_1core_1_1effect_1_1_effects_factory.html", null ],
    [ "vae::core::effect::EffectsList", "classvae_1_1core_1_1effect_1_1_effects_list.html", null ],
    [ "vae::core::EffectsProcessor", "classvae_1_1core_1_1_effects_processor.html", null ],
    [ "vae::core::Emitter", "structvae_1_1core_1_1_emitter.html", null ],
    [ "vae::core::Engine", "classvae_1_1core_1_1_engine.html", null ],
    [ "vae::EngineConfig", "structvae_1_1_engine_config.html", null ],
    [ "vae::EnginePimpl", "classvae_1_1_engine_pimpl.html", null ],
    [ "vae::core::Event", "structvae_1_1core_1_1_event.html", null ],
    [ "tklb::EventBus< EVENT_COUNT, EventId, MutexType >", "classtklb_1_1_event_bus.html", null ],
    [ "vae::EventCallbackData", "structvae_1_1_event_callback_data.html", null ],
    [ "tklb::FFTOoura", "classtklb_1_1_f_f_t_ooura.html", null ],
    [ "tklb::FFTpffft", "classtklb_1_1_f_f_tpffft.html", null ],
    [ "File", "struct_file.html", null ],
    [ "vae::core::fs::File", "classvae_1_1core_1_1fs_1_1_file.html", null ],
    [ "tklb::FileInfo", "structtklb_1_1_file_info.html", null ],
    [ "vae::core::memory::FsAllocatorName", "structvae_1_1core_1_1memory_1_1_fs_allocator_name.html", null ],
    [ "tklb::HeapBuffer< T, ALIGNMENT, ALLOCATOR, SIZE >", "classtklb_1_1_heap_buffer.html", null ],
    [ "tklb::HeapBuffer< BaseSubscription * >", "classtklb_1_1_heap_buffer.html", null ],
    [ "tklb::HeapBuffer< Buffer >", "classtklb_1_1_heap_buffer.html", null ],
    [ "tklb::HeapBuffer< char >", "classtklb_1_1_heap_buffer.html", null ],
    [ "tklb::HeapBuffer< T, DEFAULT_ALIGNMENT >", "classtklb_1_1_heap_buffer.html", null ],
    [ "tklb::HeapBuffer< T, true >", "classtklb_1_1_heap_buffer.html", [
      [ "tklb::HandleBuffer< T, Handle, MaskSplit >", "classtklb_1_1_handle_buffer.html", null ]
    ] ],
    [ "vae::core::HRTF", "structvae_1_1core_1_1_h_r_t_f.html", null ],
    [ "vae::core::HRTFLoader", "classvae_1_1core_1_1_h_r_t_f_loader.html", null ],
    [ "vae::core::HRTFUtil", "structvae_1_1core_1_1_h_r_t_f_util.html", null ],
    [ "vae::core::Listener", "structvae_1_1core_1_1_listener.html", null ],
    [ "vae::LocationDirection", "structvae_1_1_location_direction.html", null ],
    [ "vae::LocationOrientation", "structvae_1_1_location_orientation.html", null ],
    [ "tklb::LockGuard< T >", "classtklb_1_1_lock_guard.html", null ],
    [ "tklb::LockGuardTry< T >", "classtklb_1_1_lock_guard_try.html", null ],
    [ "tklb::Logger", "classtklb_1_1_logger.html", null ],
    [ "tklb::memory::tracer::MagicBlock", "structtklb_1_1memory_1_1tracer_1_1_magic_block.html", null ],
    [ "vae::core::memory::MainAllocatorName", "structvae_1_1core_1_1memory_1_1_main_allocator_name.html", null ],
    [ "tklb::MallocInfo", "structtklb_1_1_malloc_info.html", null ],
    [ "tklb::memory::MemoryPool", "classtklb_1_1memory_1_1_memory_pool.html", [
      [ "tklb::memory::MemoryPoolStack", "classtklb_1_1memory_1_1_memory_pool_stack.html", null ],
      [ "tklb::memory::MemoryPoolStd", "classtklb_1_1memory_1_1_memory_pool_std.html", null ]
    ] ],
    [ "vae::core::effect::Meta", "structvae_1_1core_1_1effect_1_1_meta.html", null ],
    [ "vae::core::Mixer", "structvae_1_1core_1_1_mixer.html", null ],
    [ "vae::core::MixerProcessor", "classvae_1_1core_1_1_mixer_processor.html", null ],
    [ "tklb::Mutex", "classtklb_1_1_mutex.html", null ],
    [ "tklb::MutexDummy", "classtklb_1_1_mutex_dummy.html", null ],
    [ "tklb::Oversampler< CHANNELS, MAX_BLOCK >", "classtklb_1_1_oversampler.html", null ],
    [ "vae::core::Effect::Parameter", "structvae_1_1core_1_1_effect_1_1_parameter.html", null ],
    [ "vae::core::HRTF::Position", "structvae_1_1core_1_1_h_r_t_f_1_1_position.html", null ],
    [ "vae::core::Processor", "classvae_1_1core_1_1_processor.html", null ],
    [ "vae::core::effect::EffectsList::RegisteredEffect", "structvae_1_1core_1_1effect_1_1_effects_list_1_1_registered_effect.html", null ],
    [ "vae::core::effect::Registermydsp", "structvae_1_1core_1_1effect_1_1_registermydsp.html", null ],
    [ "vae::core::effect::RegisterVAEReverb", "structvae_1_1core_1_1effect_1_1_register_v_a_e_reverb.html", null ],
    [ "tklb::ResamplerCosineTpl< T >", "classtklb_1_1_resampler_cosine_tpl.html", null ],
    [ "tklb::ResamplerHoldTpl< T >", "classtklb_1_1_resampler_hold_tpl.html", null ],
    [ "tklb::ResamplerLinearTpl< T, Buffer >", "classtklb_1_1_resampler_linear_tpl.html", null ],
    [ "tklb::ResamplerSpeexTpl< T, Buffer >", "classtklb_1_1_resampler_speex_tpl.html", null ],
    [ "tklb::ResamplerSpeexTpl< Sample, ScratchBuffer >", "classtklb_1_1_resampler_speex_tpl.html", null ],
    [ "vae::core::memory::ScratchAllocatorName", "structvae_1_1core_1_1memory_1_1_scratch_allocator_name.html", null ],
    [ "tklb::SectionClock", "classtklb_1_1_section_clock.html", null ],
    [ "tklb::SectionTimer", "classtklb_1_1_section_timer.html", null ],
    [ "tklb::memory::MemoryPool::SharedPool", "structtklb_1_1memory_1_1_memory_pool_1_1_shared_pool.html", null ],
    [ "vae::core::Source", "structvae_1_1core_1_1_source.html", null ],
    [ "vae::core::SourceLoader", "structvae_1_1core_1_1_source_loader.html", null ],
    [ "vae::core::SpatialManager", "classvae_1_1core_1_1_spatial_manager.html", null ],
    [ "vae::core::SpatialProcessor", "classvae_1_1core_1_1_spatial_processor.html", null ],
    [ "vae::core::SPCAP", "structvae_1_1core_1_1_s_p_c_a_p.html", null ],
    [ "vae::core::SPCAP::SPCAPConfig< N >", "classvae_1_1core_1_1_s_p_c_a_p_1_1_s_p_c_a_p_config.html", null ],
    [ "vae::core::SPCAP::SPCAPConfig< N >::Speaker", "structvae_1_1core_1_1_s_p_c_a_p_1_1_s_p_c_a_p_config_1_1_speaker.html", null ],
    [ "tklb::SpinLock", "classtklb_1_1_spin_lock.html", null ],
    [ "tklb::StackString< N >", "classtklb_1_1_stack_string.html", null ],
    [ "tklb::StackString< 16 >", "classtklb_1_1_stack_string.html", null ],
    [ "tklb::StdAllocator< T >", "structtklb_1_1_std_allocator.html", null ],
    [ "tklb::StdAllocator< unsigned char >", "structtklb_1_1_std_allocator.html", null ],
    [ "tklb::String< STORAGE >", "classtklb_1_1_string.html", null ],
    [ "tklb::String< HeapBuffer< char > >", "classtklb_1_1_string.html", null ],
    [ "vae::core::effect::UI", "structvae_1_1core_1_1effect_1_1_u_i.html", null ],
    [ "vae::Vector3", "structvae_1_1_vector3.html", null ],
    [ "vae::core::Voice", "structvae_1_1core_1_1_voice.html", null ],
    [ "vae::core::VoiceFilter", "structvae_1_1core_1_1_voice_filter.html", null ],
    [ "vae::core::VoiceHRTF", "structvae_1_1core_1_1_voice_h_r_t_f.html", null ],
    [ "vae::core::VoiceManger", "classvae_1_1core_1_1_voice_manger.html", null ],
    [ "vae::core::VoicePan", "structvae_1_1core_1_1_voice_pan.html", null ],
    [ "tklb::wave::WaveOptions", "structtklb_1_1wave_1_1_wave_options.html", null ]
];